---
on:
    workflow_dispatch:
    schedule:
        - cron: '0 0 * * *'

jobs:
    rotate:
        permissions:
            id-token: write
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: aws-actions/configure-aws-credentials@v4
              with:
                  role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
                  aws-region: ${{ secrets.AWS_REGION }}
            - uses: azure/login@v1
              with:
                  client-id: ${{ secrets.AZURE_CLIENT_ID }}
                  tenant-id: ${{ secrets.AZURE_TENANT_ID }}
                  allow-no-subscription: true
            - name: check aws creds
              run: aws sts get-caller-identity
            - name: check azure creds
              run: az account show